/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
    './.storybook/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'k10-bg':               'var(--k10-color-bg)',
        'k10-bg-deep':          'var(--k10-color-bg-deep)',
        'k10-surface':          'var(--k10-color-surface)',
        'k10-surface-raised':   'var(--k10-color-surface-raised)',
        'k10-surface-elevated': 'var(--k10-color-surface-elevated)',
        'k10-surface-4':        'var(--k10-color-surface-4)',
        'k10-primary':          'var(--k10-color-primary)',
        'k10-primary-text':     'var(--k10-color-primary-text)',
        'k10-accent':           'var(--k10-color-accent)',
        'k10-accent-text':      'var(--k10-color-accent-text)',
        'k10-secondary':        'var(--k10-color-secondary)',
        'k10-secondary-text':   'var(--k10-color-secondary-text)',
        'k10-danger':           'var(--k10-color-danger)',
        'k10-success':          'var(--k10-color-success)',
        'k10-warning':          'var(--k10-color-warning)',
        'k10-info':             'var(--k10-color-info)',
        'k10-neutral':          'var(--k10-color-neutral)',
        'k10-text':             'var(--k10-color-text)',
        'k10-text-secondary':   'var(--k10-color-text-secondary)',
        'k10-text-muted':       'var(--k10-color-text-muted)',
        'k10-border':           'var(--k10-color-border)',
      },
      fontSize: {
        'k10-display':  ['var(--k10-font-size-display)',    { lineHeight: 'var(--k10-line-height-display)' }],
        'k10-h1':       ['var(--k10-font-size-h1)',         { lineHeight: 'var(--k10-line-height-h1)' }],
        'k10-h2':       ['var(--k10-font-size-h2)',         { lineHeight: 'var(--k10-line-height-h2)' }],
        'k10-h3':       ['var(--k10-font-size-h3)',         { lineHeight: 'var(--k10-line-height-h3)' }],
        'k10-body-lg':  ['var(--k10-font-size-body-large)', { lineHeight: 'var(--k10-line-height-body-large)' }],
        'k10-body':     ['var(--k10-font-size-body)',       { lineHeight: 'var(--k10-line-height-body)' }],
        'k10-body-sm':  ['var(--k10-font-size-body-sm)',    { lineHeight: 'var(--k10-line-height-body-sm)' }],
        'k10-label':    ['var(--k10-font-size-label)',      { lineHeight: 'var(--k10-line-height-label)' }],
        'k10-caption':  ['var(--k10-font-size-caption)',    { lineHeight: 'var(--k10-line-height-caption)' }],
        'k10-data-lg':  ['var(--k10-font-size-data-lg)',    { lineHeight: 'var(--k10-line-height-data-lg)' }],
        'k10-data-md':  ['var(--k10-font-size-data-md)',    { lineHeight: 'var(--k10-line-height-data-md)' }],
        'k10-data-sm':  ['var(--k10-font-size-data-sm)',    { lineHeight: 'var(--k10-line-height-data-sm)' }],
      },
      fontFamily: {
        sans: ['var(--k10-font-family)'],
      },
      spacing: {
        'k10-xs':   'var(--k10-space-xs)',
        'k10-sm':   'var(--k10-space-sm)',
        'k10-md':   'var(--k10-space-md)',
        'k10-lg':   'var(--k10-space-lg)',
        'k10-xl':   'var(--k10-space-xl)',
        'k10-xxl':  'var(--k10-space-xxl)',
        'k10-xxxl': 'var(--k10-space-xxxl)',
        'k10-4xl':  'var(--k10-space-4xl)',
        'k10-5xl':  'var(--k10-space-5xl)',
        'k10-6xl':  'var(--k10-space-6xl)',
      },
      borderRadius: {
        'k10-xs':   'var(--k10-radius-xs)',
        'k10-sm':   'var(--k10-radius-sm)',
        'k10-md':   'var(--k10-radius-md)',
        'k10-lg':   'var(--k10-radius-lg)',
        'k10-xl':   'var(--k10-radius-xl)',
        'k10-2xl':  'var(--k10-radius-2xl)',
        'k10-full': 'var(--k10-radius-full)',
      },
      boxShadow: {
        'k10-sm':          'var(--k10-shadow-sm)',
        'k10-md':          'var(--k10-shadow-md)',
        'k10-lg':          'var(--k10-shadow-lg)',
        'k10-xl':          'var(--k10-shadow-xl)',
        'k10-focus':       'var(--k10-shadow-focus)',
        'k10-glow':        'var(--k10-shadow-primary-glow)',
        'k10-accent-glow': 'var(--k10-shadow-accent-glow)',
      },
      transitionDuration: {
        'k10-fast':   'var(--k10-duration-fast)',
        'k10-normal': 'var(--k10-duration-normal)',
        'k10-slow':   'var(--k10-duration-slow)',
      },
    },
  },
  plugins: [],
};
